docs: Retrieve README
aneoconsulting/ArmoniK pull request #1083
Opened 2023-05-16 16:02 UTC by lzianekhodja

2023-05-16 17:33 UTC, alouvion-aneo approved these changes

2023-05-17 06:20 UTC, lemaitre-aneo requested changes
This doc should not be recreated here, and most of it already exist: https://aneoconsulting.github.io/ArmoniK/installation

The best way forward is to changes links in the README to this doc, and fill the gap in https://github.com/aneoconsulting/ArmoniK/tree/main/.docs/content

2023-05-17 06:32 UTC, lzianekhodja commented
We need to fill in the gaps and have the new documentation ready before deleting the old documentation. 
There are still READMEs that point to enixisting files and new users are still getting the 404 error and the site is still not as convenient.

2023-05-17 11:11 UTC, esoubiran-aneo commented on infrastructure/README.md
> +# Quick install of ArmoniK
https://aneoconsulting.github.io/ArmoniK/installation

2023-05-17 11:15 UTC, esoubiran-aneo requested changes

2023-05-17 11:15 UTC, esoubiran-aneo commented on infrastructure/docs/all-in-one-deploy.md
Ce fichier a effectivement été supprimé mais je pense qu'il faut y mettre plus d'explication (ou plus d'explication sur ArmoniK) parce qu'en l'état, il n'est pas utilisable.

2023-05-17 11:15 UTC, esoubiran-aneo commented on infrastructure/docs/k3s.md
https://aneoconsulting.github.io/ArmoniK/installation/linux/prerequisites#installation

https://aneoconsulting.github.io/ArmoniK/installation/linux/prerequisites#k3s

2023-05-17 11:15 UTC, esoubiran-aneo commented on infrastructure/docs/k3s.md
Ce fichier n'est à mon avis pas utile.

2023-05-17 11:15 UTC, esoubiran-aneo commented on infrastructure/docs/wsl2.md
Mis à jour dans la documentation (avec une version pour systemd qui simplifie grandement l'installation).

https://aneoconsulting.github.io/ArmoniK/installation/windows/wsl2-with-systemd
https://aneoconsulting.github.io/ArmoniK/installation/windows/wsl2-with-genie

2023-05-17 11:15 UTC, esoubiran-aneo commented on infrastructure/quick-deploy/localhost/README.md
Dans la documentation 

https://aneoconsulting.github.io/ArmoniK/installation/linux/installation
https://aneoconsulting.github.io/ArmoniK/installation/linux/verify-installation

2023-05-17 11:20 UTC, lzianekhodja commented
Let's finalize the documentation first, while updating the existing. 
If we want to remove these files, we must first update the READMEs that point to links that return 404 errors.

2023-05-17 11:23 UTC, esoubiran-aneo commented
> We need to fill in the gaps and have the new documentation ready before deleting the old documentation. There are still READMEs that point to enixisting files and new users are still getting the 404 error and the site is still not as convenient.

Je suis désolé mais je ne vois pas où se trouve la documentation actuelle. Les quelques README éparpillés dans le repo ne sont pas maintenable pour nous mais surtout sont très difficile à utiliser par la suite rendant complexe l'intégration de nouveaux contributeurs.

Il est vrai que la nouvelle documentation (en ligne) n'est pas complète mais jusqu'à preuve du contraire, pas grand monde participe à sa création. Il se trouve que Rome ne s'est pas fait en 1 jour et il en sera de même pour celle d'ArmoniK évidemment. Mais si on ne commence jamais à s'y mettre, on n'y arrivera effectivement jamais.

Pour information, des issues ont été ouvertes et assignés à des membres de l'équipe mais jamais complétées.

https://github.com/aneoconsulting/ArmoniK/issues/1004
https://github.com/aneoconsulting/ArmoniK/issues/1035
https://github.com/aneoconsulting/ArmoniK/issues/1034
https://github.com/aneoconsulting/ArmoniK/issues/1025
https://github.com/aneoconsulting/ArmoniK/issues/991
https://github.com/aneoconsulting/ArmoniK/issues/965
https://github.com/aneoconsulting/ArmoniK.Core/issues/252
https://github.com/aneoconsulting/ArmoniK.Core/issues/254
https://github.com/aneoconsulting/ArmoniK.Core/issues/253
https://github.com/aneoconsulting/ArmoniK.Core/issues/337
https://github.com/aneoconsulting/ArmoniK.Core/issues/209
https://github.com/aneoconsulting/ArmoniK.Community/issues/7
https://github.com/aneoconsulting/ArmoniK.Community/issues/6
https://github.com/aneoconsulting/ArmoniK.Community/issues/5
https://github.com/aneoconsulting/ArmoniK.Community/issues/4

En ce qui concerne les README qui ont des liens vers nulle part, il ne faut pas hésiter à faire des pull requests pour les changer et les mettre à jour !

> the site is still not as convenient

Sur ce point, je serai ravi d'avoir des retours. https://github.com/aneoconsulting/ArmoniK-docs-theme

2023-05-17 12:21 UTC, lzianekhodja commented
Je ne dis pas le contraire. Je suis complètement d'accord, la documentation n'est pas encore complète et celle d'avant faut la mettre à jour. Nous devons le faire au fur et à mesure.
Je signale seuelement qu'avant de supprimer des fichiers qui généreront des erreurs 404, il faut d'abord tout déplacer et supprimer les README qui pointent vers des liens inexistants ou remplacer ces liens vers la nouvelle documentation.

2023-05-17 13:05 UTC, YKharouni approved these changes

2023-05-23 05:43 UTC, closed without merging