docs(split_deploy):Fix deployment documentation for missing command
aneoconsulting/ArmoniK pull request #1183
Opened 2023-07-24 08:41 UTC by iadjadj

Ensure proper functionality by fixing missing command in deployment documentation

2023-07-24 16:45 UTC, esoubiran-aneo approved these changes

2023-08-02 13:44 UTC, pmilaneo commented on .docs/content/1.installation/1.linux/1.installation.md
> +If you don't create a Kubernetes namespace, the deployment will failed.
```suggestion
If you do not create a Kubernetes namespace, the deployment will fail.
```

2023-08-02 13:44 UTC, pmilaneo commented on .docs/content/1.installation/1.linux/1.installation.md
> +Now, you have the ability to deploy each resource independently :
```suggestion
Now, you can deploy each resource independently :
```

2023-08-02 13:46 UTC, pmilaneo requested changes
a few changes and it's ok

2023-08-03 17:53 UTC, lzianekhodja approved these changes

2023-08-04 08:49 UTC, pmilaneo requested changes
there is line 38 to change into
If you do not create the data directory, the deployment will fail when the compute plane tries to mount the shared directory.
sorry, I missed it during the first review

2023-08-04 10:34 UTC, lzianekhodja submitted a review, later dismissed

2023-08-04 10:34 UTC, lzianekhodja commented
> there is line 38 to change into If you do not create the data directory, the deployment will fail when the compute plane tries to mount the shared directory. sorry, I missed it during the first review

Yes off course, this is what was explained in the old documentation in Markdown files at the root of the deployment project.

2023-08-04 12:25 UTC, pmilaneo requested changes
how that should be good

2023-08-09 11:54 UTC, lzianekhodja approved these changes

2023-08-21 08:44 UTC, aneojgurhem commented
@iadjadj can you resolve the conflict ?
@pmilaneo you should approve when the conflict are resolved because your requested changes are blocking the merge

2023-08-24 07:15 UTC, pmilaneo submitted a review, later dismissed

2023-09-01 16:10 UTC, merged